spring:
  activemq:
    broker-url: tcp://localhost:61616

  jms:
    pub-sub-domain: true # 訂閱模式
    # template:
    # # 統一佇列名稱,不建議
    #   default-destination: message-prefix
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest