server:
  port: 80
spring:
  datasource:
    druid:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/spring_test?serverTimezone=UTC
        username: root
        password: 
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml

  # redis:
  #   host: localhost
  #   port: 6379 
  # cache:
  #   type: redis 
  #   redis:
  #     use-key-prefix: true # 是否使用前缀名（系统設定前缀名）
  #     key-prefix: sms_ # 追加白定义前缀名
  #     time-to-live: 10s # 有效时长
  #     cache-null-values: false # 是否允许存储空值

logging:
  pattern:
    level: debug
    
mybatis-plus:
  global-config:
    db-config:
      id-type: assign-id
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl