cartoon:
    cat:
        name: "cat2"
        age: 6
    mouse:
        name: "mouse2"
        age: 3

# spring:
#   autoconfigure:
#     exclude:
#     - com.example.springboot_16_bean_propertise.bean.CartoonCatAndMouse