# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/spring_test?serverTimezone=UTC
#     hikari:
#       username: root
#       password: root
#       driver-class-name: com.mysql.cj.jdbc.Driver
    #   type: com.alibaba.druid.pool.DruidDataSource

    #  hikari可以拉出來配置，但是注意url不行，要吃通用配置(上一層)
    #   hikari:
    #     username: root
    #     password: root
    #     driver-class-name: com.mysql.cj.jdbc.Driver
    #     maximum-pool-size: 50
logging:
  pattern:
    level: debug
    
# mybatis-plus:
#   global-config:
#     db-config:
#       id-type: assign-id
#   configuration:
#     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# H2 設定

server:
  port: 80
spring:
  h2:
    console:
      path: /h2
      # 正式需改成false
      enabled: true
  # 初始化需設定一次，後可以刪除
  datasource:
    url: jdbc:h2:~/test
    hikari:
      username: sa
      password: 123456
      # 可寫可不寫
      # driver-class-name: org.h2.Driver
mybatis-plus:
  global-config:
    db-config:
      id-type: assign-id
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl