spring:
  data:
    redis:
    #  默認值 6379 localhost
      port: 6379
      host: localhost
      # 預設 lettuce ，可改成jedis
      client-type: lettuce
      lettuce:
        pool:
          max-active: 16